### ISSUE TITLE
Warning class implements device_state_attributes

### ISSUE THREAD

**Issue by gerliczky** [vanstinator/hass-raincloud#10]
With HA version 2021.12 warnings appeared on the log, complaining about the implementation of device_state_attributes.

> (<class 'custom_components.raincloud.binary_sensor.RainCloudBinarySensor'>) implements device_state_attributes. Please report it to the custom component author.
(<class 'custom_components.raincloud.switch.RainCloudSwitch'>) implements device_state_attributes. Please report it to the custom component author.
(<class 'custom_components.raincloud.sensor.RainCloudSensor'>) implements device_state_attributes. Please report it to the custom component author.

Could you please take a look at it, if you have time?

**Comment by vanstinator** [comment]
Fixed and shipped!
