### ISSUE TITLE
Unable to prepare setup for platform raincloud.binary_sensor

### ISSUE THREAD

**Issue by wildoracle** [vanstinator/hass-raincloud#11]
Logger: homeassistant.setup
Source: setup.py:298
First occurred: 3:45:29 AM (3 occurrences)
Last logged: 3:45:33 AM

Unable to prepare setup for platform raincloud.binary_sensor: Unable to set up component.
Unable to prepare setup for platform raincloud.switch: Unable to set up component.
Unable to prepare setup for platform raincloud.sensor: Unable to set up component.

Version | core-2022.5.5
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.9
Operating System Family | Linux
Operating System Version | 5.15.41
CPU Architecture | x86_64
Timezone | America/Vancouver

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.25.1
Stage | running
Available Repositories | 1134
Downloaded Repositories | 47

Host Operating System | Home Assistant OS 8.1
-- | --
Update Channel | stable
Supervisor Version | supervisor-2022.05.3
Docker Version | 20.10.14
Disk Total | 125.3 GB
Disk Used | 14.5 GB
Healthy | true
Supported | true
Board | ova
Supervisor API | ok
Version API | ok
Installed Add-ons | Samba share (9.6.1), File editor (5.3.3), Check Home Assistant configuration (3.10.0), Mosquitto broker (6.1.2), AirCast (3.3.0), AdGuard Home (4.5.1), SSH & Web Terminal (10.1.3), ESPHome (2022.3.1), TasmoBackup (1.04.26), Let's Encrypt (4.12.2), Home Assistant Google Drive Backup (0.107.2), AppDaemon (0.8.2)

**Comment by grahamr** [comment]
My guess is it’s tied to their SSL cert expiration issue.  The certificate for the site expired earlier in the week and they are working on fixing it according to twitter

https://twitter.com/melnor_inc/status/1528847406271438848?s=21&t=Q0R8cJBugupiD_bHQdrVXQ

https://twitter.com/melnor_inc/status/1529586933017591814?s=21&t=Q0R8cJBugupiD_bHQdrVXQ

**Comment by vanstinator** [comment]
2 years ago when they did this they used a cert with a weird signing authority and I ended up having to pin the chain in the core python lib to unbreak ssl verification.

The website started working over the weekend and that pinned cert starting causing issues. I've pulled it out and pushed another release.

**Comment by wildoracle** [comment]
Thank you @vanstinator !!
