### ISSUE TITLE
Integration not working

### ISSUE THREAD

**Issue by ynormand** [vanstinator/hass-raincloud#2]
HI,
I'm trying to connect RainCloud to homeassistant.

here log error:

The following integrations and platforms could not be set up:

raincloud
raincloud.binary_sensor
raincloud.sensor

**Comment by gerliczky** [comment]
Could you please show your configuration?

**Comment by ynormand** [comment]
# raincloud
raincloud:
  username: !secret melnoruser
  password: !secret melnorpass
binary_sensor:
  - platform: raincloud
[...]
sensor:
[...] #i have many other sensors
  - platform: raincloud

**Comment by ynormand** [comment]
oups, code not translate as code.
Here the code
`# raincloud
raincloud:
  username: !secret melnoruser
  password: !secret melnorpass
binary_sensor:
  - platform: raincloud`

**Comment by ynormand** [comment]
[raincloud.txt](https://github.com/vanstinator/hass-raincloud/files/4672598/raincloud.txt)

**Comment by vanstinator** [comment]
What version are you installing? Are you using HACS?

**Comment by ynormand** [comment]
Hostname | hassio System | HassOS 3.12
Home Assistant Core running version 0.107.7

**Comment by vanstinator** [comment]
Have you installed the custom component or are you using the default built in to home assistant

**Comment by ynormand** [comment]
default build.

**Comment by vanstinator** [comment]
That version is no longer supported and will be removed from home assistant
in the near future. You'll need to install the custom version going
forward.

**Comment by ynormand** [comment]
Where can i find the correct version?

**Comment by ynormand** [comment]
And how to install it on my system?

**Comment by vanstinator** [comment]
I wrote some basic docs this morning that should help https://github.com/vanstinator/hass-raincloud#installation
