### ISSUE TITLE
Error on setup

### ISSUE THREAD

**Issue by TheRealWaldo** [vanstinator/hass-raincloud#9]
```
This error originated from a custom integration.

Logger: custom_components.raincloud
Source: custom_components/raincloud/__init__.py:113
Integration: Melnor RainCloud (documentation)
First occurred: 3:37:39 PM (1 occurrences)
Last logged: 3:37:39 PM

Unable to connect to Rain Cloud service: 500 Server Error: Internal Server Error for url: https://wifiaquatimer.com/get_cu_and_fu_status?controller_serial=**REDACTED**&faucet_serial=**REDACTED**
```

I'm unable to use the integration after moving to a new controller.  It seems the integration still tries to access it, even though it was removed from the server-side.  

How does one go about removing the old controller/valve units from this integration?

**Comment by vanstinator** [comment]
Is the old controller still connected to your raincloud account? The integration pulls all listed controllers from there before trying to parse out the valve info. We don't cache any of that info in HA and wouldn't be hitting the status update endpoint any other way.

**Comment by TheRealWaldo** [comment]
The old controller was removed from the raincloud account.  I found that I had to uninstall the integration, then manually find and delete all of the entities that the integration created to get it to run again.

I've since abandoned trying to get it working however, the raincloud devices won't even connect on their own anymore.
